# ... (rest of the file)
nav:
  - Introduction: main.md
  - System Architecture: 
    - SCADA Overview: main.md
    # ... (add all your .md files here)

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - search.suggest
    - search.highlight 
plugins:
  # This ensures the search function is active and indexes your content
  - search